language: node_js

node_js:
  - "8"

cache: yarn

install:
  - yarn

before_script:
  - yarn selenium:install
  - yarn selenium:start

script:
  - yarn lint
  - yarn test --coverage

after_script:
  - yarn publish
